apiVersion: v1
data:
  mapRoles: | 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::381346698658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QOQI9TDNI0GB
      username: system:node:{{EC2PrivateDNSName}}\n"
    - groups:
      - system:masters
      rolearn: arn:aws:iam::381346698658:role/UdacityFlaskDeployCBKubectlRole
      username: build        
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-17T04:01:01Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-06-17T04:01:01Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-06-17T04:07:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2857"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f15c3af8-dcd4-431e-989c-74bf5113ad52
