apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::920669063016:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RVZ6UULWCLS7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::920669063016:role/UdacityFlaskDeployCBKubectlRole
      username: build      
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-18T15:09:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-06-18T15:09:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2066"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 06bf7907-f646-48ee-90a6-b50fb3c60c36
